"""first version

Revision ID: 531d0960080d
Revises: 
Create Date: 2023-05-16 09:21:53.408880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531d0960080d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('responsible', sa.String(length=100), nullable=True),
    sa.Column('coordinator', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.Column('service_description', sa.String(), nullable=True),
    sa.Column('knowledge', sa.String(), nullable=True),
    sa.Column('interfaces', sa.String(), nullable=True),
    sa.Column('mission_critical', sa.String(), nullable=True),
    sa.Column('support_contracts', sa.String(), nullable=True),
    sa.Column('security_supplier', sa.String(), nullable=True),
    sa.Column('user_amount', sa.Integer(), nullable=True),
    sa.Column('scope_description', sa.String(), nullable=True),
    sa.Column('risk_assessment_human', sa.String(), nullable=True),
    sa.Column('risk_assessment_process', sa.String(), nullable=True),
    sa.Column('risk_assessment_technological', sa.String(), nullable=True),
    sa.Column('project_leader', sa.String(), nullable=True),
    sa.Column('risk_owner', sa.String(), nullable=True),
    sa.Column('product_owner', sa.String(), nullable=True),
    sa.Column('technical_administrator', sa.String(), nullable=True),
    sa.Column('security_manager', sa.String(), nullable=True),
    sa.Column('incident_contact', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consequence_category', sa.String(), nullable=True),
    sa.Column('consequence_small', sa.String(), nullable=True),
    sa.Column('consequence_medium', sa.String(), nullable=True),
    sa.Column('consequence_large', sa.String(), nullable=True),
    sa.Column('consequence_huge', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bia_name', sa.Integer(), nullable=True),
    sa.Column('component_name', sa.String(), nullable=True),
    sa.Column('processes_dependencies', sa.String(), nullable=True),
    sa.Column('info_type', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bia_name'], ['context_scope.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_name', sa.Integer(), nullable=True),
    sa.Column('mtd', sa.String(), nullable=True),
    sa.Column('rto', sa.String(), nullable=True),
    sa.Column('rpo', sa.String(), nullable=True),
    sa.Column('masl', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['component_name'], ['components.component_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_name', sa.Integer(), nullable=True),
    sa.Column('cat_avail_finance_real', sa.String(), nullable=True),
    sa.Column('cat_avail_operational_real', sa.String(), nullable=True),
    sa.Column('cat_avail_regulatory_real', sa.String(), nullable=True),
    sa.Column('cat_avail_reputation_trust_real', sa.String(), nullable=True),
    sa.Column('cat_avail_human_safety_real', sa.String(), nullable=True),
    sa.Column('cat_avail_privacy_real', sa.String(), nullable=True),
    sa.Column('just_avail_finance_real', sa.String(), nullable=True),
    sa.Column('just_avail_operational_real', sa.String(), nullable=True),
    sa.Column('just_avail_regulatory_real', sa.String(), nullable=True),
    sa.Column('just_avail_reputation_trust_real', sa.String(), nullable=True),
    sa.Column('just_avail_human_safety_real', sa.String(), nullable=True),
    sa.Column('just_avail_privacy_real', sa.String(), nullable=True),
    sa.Column('cat_integrity_finance_real', sa.String(), nullable=True),
    sa.Column('cat_integrity_operational_real', sa.String(), nullable=True),
    sa.Column('cat_integrity_regulatory_real', sa.String(), nullable=True),
    sa.Column('cat_integrity_reputation_trust_real', sa.String(), nullable=True),
    sa.Column('cat_integrity_human_safety_real', sa.String(), nullable=True),
    sa.Column('cat_integrity_privacy_real', sa.String(), nullable=True),
    sa.Column('just_integrity_finance_real', sa.String(), nullable=True),
    sa.Column('just_integrity_operational_real', sa.String(), nullable=True),
    sa.Column('just_integrity_regulatory_real', sa.String(), nullable=True),
    sa.Column('just_integrity_reputation_trust_real', sa.String(), nullable=True),
    sa.Column('just_integrity_human_safety_real', sa.String(), nullable=True),
    sa.Column('just_integrity_privacy_real', sa.String(), nullable=True),
    sa.Column('cat_conf_finance_real', sa.String(), nullable=True),
    sa.Column('cat_conf_operational_real', sa.String(), nullable=True),
    sa.Column('cat_conf_regulatory_real', sa.String(), nullable=True),
    sa.Column('cat_conf_reputation_trust_real', sa.String(), nullable=True),
    sa.Column('cat_conf_human_safety_real', sa.String(), nullable=True),
    sa.Column('cat_conf_privacy_real', sa.String(), nullable=True),
    sa.Column('just_conf_finance_real', sa.String(), nullable=True),
    sa.Column('just_conf_operational_real', sa.String(), nullable=True),
    sa.Column('just_conf_regulatory_real', sa.String(), nullable=True),
    sa.Column('just_conf_reputation_trust_real', sa.String(), nullable=True),
    sa.Column('just_conf_human_safety_real', sa.String(), nullable=True),
    sa.Column('just_conf_privacy_real', sa.String(), nullable=True),
    sa.Column('cat_avail_finance_worst', sa.String(), nullable=True),
    sa.Column('cat_avail_operational_worst', sa.String(), nullable=True),
    sa.Column('cat_avail_regulatory_worst', sa.String(), nullable=True),
    sa.Column('cat_avail_reputation_trust_worst', sa.String(), nullable=True),
    sa.Column('cat_avail_human_safety_worst', sa.String(), nullable=True),
    sa.Column('cat_avail_privacy_worst', sa.String(), nullable=True),
    sa.Column('just_avail_finance_worst', sa.String(), nullable=True),
    sa.Column('just_avail_operational_worst', sa.String(), nullable=True),
    sa.Column('just_avail_regulatory_worst', sa.String(), nullable=True),
    sa.Column('just_avail_reputation_trust_worst', sa.String(), nullable=True),
    sa.Column('just_avail_human_safety_worst', sa.String(), nullable=True),
    sa.Column('just_avail_privacy_worst', sa.String(), nullable=True),
    sa.Column('cat_integrity_finance_worst', sa.String(), nullable=True),
    sa.Column('cat_integrity_operational_worst', sa.String(), nullable=True),
    sa.Column('cat_integrity_regulatory_worst', sa.String(), nullable=True),
    sa.Column('cat_integrity_reputation_trust_worst', sa.String(), nullable=True),
    sa.Column('cat_integrity_human_safety_worst', sa.String(), nullable=True),
    sa.Column('cat_integrity_privacy_worst', sa.String(), nullable=True),
    sa.Column('just_integrity_finance_worst', sa.String(), nullable=True),
    sa.Column('just_integrity_operational_worst', sa.String(), nullable=True),
    sa.Column('just_integrity_regulatory_worst', sa.String(), nullable=True),
    sa.Column('just_integrity_reputation_trust_worst', sa.String(), nullable=True),
    sa.Column('just_integrity_human_safety_worst', sa.String(), nullable=True),
    sa.Column('just_integrity_privacy_worst', sa.String(), nullable=True),
    sa.Column('cat_conf_finance_worst', sa.String(), nullable=True),
    sa.Column('cat_conf_operational_worst', sa.String(), nullable=True),
    sa.Column('cat_conf_regulatory_worst', sa.String(), nullable=True),
    sa.Column('cat_conf_reputation_trust_worst', sa.String(), nullable=True),
    sa.Column('cat_conf_human_safety_worst', sa.String(), nullable=True),
    sa.Column('cat_conf_privacy_worst', sa.String(), nullable=True),
    sa.Column('just_conf_finance_worst', sa.String(), nullable=True),
    sa.Column('just_conf_operational_worst', sa.String(), nullable=True),
    sa.Column('just_conf_regulatory_worst', sa.String(), nullable=True),
    sa.Column('just_conf_reputation_trust_worst', sa.String(), nullable=True),
    sa.Column('just_conf_human_safety_worst', sa.String(), nullable=True),
    sa.Column('just_conf_privacy_worst', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['component_name'], ['components.component_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consequences')
    op.drop_table('availability_requirements')
    op.drop_table('components')
    op.drop_table('references')
    op.drop_table('context_scope')
    # ### end Alembic commands ###
