"""third version

Revision ID: 89a2a23a760b
Revises: 03d44706a4ee
Create Date: 2023-05-16 12:13:27.579048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a2a23a760b'
down_revision = '03d44706a4ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consequences', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('consequences', 'category_realisticcase')
    op.drop_column('consequences', 'category_worstcase')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consequences', sa.Column('category_worstcase', sa.VARCHAR(), nullable=True))
    op.add_column('consequences', sa.Column('category_realisticcase', sa.VARCHAR(), nullable=True))
    op.drop_column('consequences', 'category')
    # ### end Alembic commands ###
