"""add extra table

Revision ID: ce3a5bd0f72a
Revises: 98ce49df68eb
Create Date: 2023-05-25 08:42:23.214554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3a5bd0f72a'
down_revision = '98ce49df68eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('info_owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'info_owner')
    # ### end Alembic commands ###
