"""fourth version

Revision ID: f22e9161a705
Revises: 89a2a23a760b
Create Date: 2023-05-16 12:26:58.314799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22e9161a705'
down_revision = '89a2a23a760b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consequence_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('choices')
    op.add_column('consequences', sa.Column('security_property', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consequences', 'security_property')
    op.create_table('choices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('choice', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('security_properties')
    op.drop_table('consequence_choices')
    # ### end Alembic commands ###
