version: '3.8'

services:
  bia-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DATABASE_TYPE=mariadb
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=bia_tool
      - DB_USER=bia_user
      - DB_PASSWORD=${DB_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=production
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - app_logs:/app/logs
      - app_instance:/app/instance
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mariadb:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=bia_tool
      - MYSQL_USER=bia_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb_prod_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mariadb_prod_data:
  app_logs:
  app_instance: