# Dit is de naam van de workflow, zichtbaar in de "Actions" tab van GitHub.
name: Deploy to Remote Server

on:
  push:
    branches: [ main ]

jobs:
  deploy-python-app:
    name: Deploy Python App to Remote Server
    # Draait op een standaard GitHub runner. Kan ook een andere self-hosted runner zijn.
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Code uitchecken op de runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Stap 2: Synchroniseer bestanden en voer deploy-commando's uit op de doelserver
      - name: Deploy to Server via SSH
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          # Secrets uit je repository-instellingen
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          
          # Kopieer de huidige map (op de runner) naar de doelmap op de server
          SOURCE: "./"
          TARGET: ${{ secrets.TARGET_DIR }}
          
          # Sluit onnodige bestanden uit
          EXCLUDE: "/.git/, /.github/, /__pycache__/, *.pyc, .env"
          
          # Commando's die worden uitgevoerd OP DE DOELSERVER nadat de bestanden zijn gekopieerd
          script: |
            echo "--- Starting deployment on remote server ---"
            
            # Definieer de paden op de remote server voor leesbaarheid
            PROJECT_DIR=${{ secrets.TARGET_DIR }}
            VENV_DIR=/home/ferry/venv/bia_app_venv # Pas aan indien nodig

            echo "1. Installing dependencies..."
            # Gebruik het absolute pad naar pip in de venv
            $VENV_DIR/bin/pip install -r $PROJECT_DIR/requirements.txt
            
            echo "2. Running database migrations..."
            # Voer 'flask' uit vanuit de venv in de juiste projectmap
            cd $PROJECT_DIR
            export FLASK_APP=run.py
            $VENV_DIR/bin/flask db upgrade
            
            echo "3. Restarting application service..."
            # Dit vereist dat de remote user (ferry) wachtwoordloze sudo-rechten heeft
            sudo systemctl restart bia
            
            echo "--- Deployment finished successfully! ---"
